#General mod settings
[general]
	#Enables or disables idle visual in the server player list tab screen
	showIdleStatesInPlayerList = true
	#Sends when you open a Gui, and what Gui
	sendActiveGui = true
	#Plays a sutble sound when a player clicks their mouse in a Gui
	playMouseClickSounds = true
	#Plays a sound when a player opens some Guis
	playScreenOpenSounds = true
	#Enables or disables the non typing animations used when showing the open Gui, such as head looking, arms moving up, arms pointing and clicking
	showPlayerAnimation_Gui = true
	#Show the chat typing Gui in world
	showPlayerActiveChatGui = true
	#Adjust the X position where the 'Player is typing...' text shows in the chat Gui
	#Range: > 0
	screenTypingRelativePosition_X = 0
	#Enables or disables idle animation
	showPlayerAnimation_Idle = true
	#Adjust the Y position where the 'Player is typing...' text shows in the chat Gui
	#Range: > 0
	screenTypingRelativePosition_Y = 0
	#Sends relative mouse position and clicking
	sendMouseInfo = true
	#String to use next to the typing player(s) name
	screenTypingText = " is typing"
	#Sends a calculated rate of typing. If off, uses a default value on server
	sendTypingSpeed = true
	#Show any Gui they're using that isn't chat typing related in world
	showPlayerActiveNonChatGui = true
	#Sends when you go idle / return
	sendIdleState = true
	#Max characters allowed before it switches to using string set in screenTypingMultiplePlayersText
	#Range: > 0
	screenTypingCharacterLimit = 50
	#Enables or disables idle visual above player head
	showIdleStatesInPlayerAboveHead = true
	#Setting false disables all animations
	showPlayerAnimations = true
	#String to use when too many people are typing determined by screenTypingCharacterLimit
	screenTypingMultiplePlayersText = "Several people are typing"
	#Enables or disables typing animation
	showPlayerAnimation_Typing = true
	#Show 'Player is typing...' on the chat screen
	screenTypingVisible = true
	#This is for the older non dynamic GUI only. If there isnt an exact Gui available for what the player is using, it will show the Chest Gui. If this is false, it will show nothing, lots of modded Guis will use this for now
	showPlayerActiveGuiIfNotExactMatch = true
	#SETTING THESE CLIENT SIDE SETTINGS TO FALSE WILL OVERRIDE ANY OF THE SAME SERVER SETTINGS THAT ARE SET TO TRUE (for your client only)
	dummySetting = true
	#Adjusts the size of the gui visual that appears infront of a player, 2 = twice the size
	#Range: 0.1 ~ 1.7976931348623157E308
	particleSizeScale = 1.0
	#Delay between ticks your client will accept and update new image of another players gui, you can only increase the delay from what the server/other client is set to, 10 = twice a second
	#Range: > 0
	tickReceiveAndRenderRateOfGUIUpdates = 10
	#Privacy setting, if you dont want to send very detailed info of your screen for everyone to see and instead use the old basic gui visual, set this to true
	dontSendDetailedGUIInfo = false
	#Privacy setting, if you dont want to show the items you are transferring to and from yourself and containers, set this to true
	dontSendItemInfo = false
